services:
  - type: web
    name: gpt-app-service
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: |
      export TESSERACT_PATH=$(which tesseract)
      export POPPLER_PATH=$(which pdfimages) # poppler-utils provides pdfimages, which is used for PDF processing
      echo "Tesseract Path: $TESSERACT_PATH" 
      echo "Poppler Path: $POPPLER_PATH" 
      if [ -f "$TESSERACT_PATH" ]; then
          echo "Tesseract was found successfully."
      else
          echo "Tesseract is missing or the path is incorrect."
      fi
      gunicorn GPT-App:app -b 0.0.0.0:10000
